# Generated by Django 4.2.1 on 2023-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designation',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='deg',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
